web:
  build: .
  command: python /code/app/app.py
  ports:
   - "5000:5000"
  links:
   - db
  volumes:
   - .:/code
  hostname: myappserver
db:
  hostname: mysqlserver
  image: orchardup/mysql
  environment:
     MYSQL_ROOT_PASSWORD: p@ssw0rd123
     MYSQL_DATABASE: wordpress
  volumes:
   - ./database:/var/lib/mysql
